# Generated by Django 2.1.4 on 2018-12-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_url', models.CharField(default='127.0.0.1', max_length=500)),
                ('backend_port', models.IntegerField(default=8205)),
            ],
        ),
    ]
