# Generated by Django 2.1.4 on 2018-12-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='config_type',
            field=models.CharField(default='local', max_length=200),
        ),
    ]
